### PR TITLE
Navigation bar

### PR DESCRIPTION
**Pull request by Grkrz**
Hej is it possible to add the option to remove this stupid navigation bar?

### CODE REVIEW

**Comment by thestinger** [comment]
I think you opened this pull request by mistake.

**Comment by Grkrz** [comment]
I just could not find a place where I can ask the graphenos teem to please if they can remove the navigation bar.

**Comment by thestinger** [comment]
What navigation bar?

**Comment by Grkrz** [comment]
The gesture navigation (white)bar on the bottom of the screen.

**Pull request closed without merging**
